//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESLevelEditor2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Config { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
